version: 0.2

env:
  variables:
    IMAGE_NAME: employee-app
    IMAGE_TAG: latest

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies"
      - pip install --upgrade pip
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo "Login to DockerHub"
      - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      - echo "Running Django checks"
      - python manage.py check

  build:
    commands:
      - echo "Build started on $(date)"
      - docker build -t $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG .

  post_build:
    commands:
      - echo "Pushing Docker image"
      - docker push $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG

artifacts:
<<<<<<< HEAD
  files:
    - appspec.yml
    - scripts/**/*
=======
 files:
  - '**/*'
>>>>>>> 477bd21aab51d2295adb56e786feac1be2fb27dd
